import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Header } from "@/components/Page/Header";
import { Sidebar } from "@/components/Page/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter" className="h-full bg-base-200">
      <body className={`${inter.className} h-full`}>
        <Header />
        <div className="flex h-full">
          <Sidebar />
          <div className="sm:ml-16 mt-16 w-full h-full">
            <AppRouterCacheProvider>
              {children}
            </AppRouterCacheProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
